### ISSUE TITLE
Error running storybook in node 18

### ISSUE THREAD

**Issue by jfee-linz** [linz/step-ag-grid#186]
When starting storybook on WSL with node 18, receive the following error:

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/jfee/code/step-ag-grid/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/jfee/code/step-ag-grid/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/jfee/code/step-ag-grid/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/jfee/code/step-ag-grid/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/jfee/code/step-ag-grid/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/jfee/code/step-ag-grid/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/jfee/code/step-ag-grid/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at /home/jfee/code/step-ag-grid/node_modules/loader-runner/lib/LoaderRunner.js:205:4 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
```

Workaround ( from https://github.com/webpack/webpack/issues/14532 )

```bash
export NODE_OPTIONS=--openssl-legacy-provider
npm run storybook
```

**Comment by matttdawson** [comment]
Is this a webpack upgrade required thing?  If so you're welcome to submit a PR for the upgrade.  I had many issues trying the upgrade, but maybe you will succeed!
If not, could we add the --openssl-legacy-provider to the build and would it work on every version of node?

**Comment by jfee-linz** [comment]
I tried setting the environment variable system wide, but it interferes with VSCode and other libraries.

I'll try upgrading, wasn't sure if that would interfere with other applications that reference this as a dependency.

**Comment by matttdawson** [comment]
It shouldn't affect other applications it was purely a dev thing.  The issue seemed to be the build webpack conflicting with storybook webpack, even though both were updated.

**Comment by jfee-linz** [comment]
For now, I can use node 16 when working with this project.
