### ISSUE TITLE
Sortable icon not showing 

### ISSUE THREAD

**Issue by egeofalcao** [linz/step-ag-grid#42]
**Bug description**
The icon (arrow up) of a sortable column does not show up in the column header until we click on it.

**To Reproduce**
1. Render a Grid with a sortable column
2. Notice the icon to sort column does not show
3. Click in the header
4. The icon appears

**Expected behavior**
The icon should show up once the Grid is rendered

**Screenshots**
![sortable icon](https://user-images.githubusercontent.com/70115704/198423201-5bd287ec-a5d9-4f91-858a-125347a9582b.gif)

**Comment by matttdawson** [comment]
Did you pass something like this on the colDef?  The default sort is whatever the natural sort of the row data is.
```
initialSort: "asc"
```
